name: GMAIL PASSWORD

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secret in a script
      run: echo "My secret is ${{ secrets.GMAIL_PASSWORD }}"
